#### First image: sha256:3eecc73bc1577262d0d977c60f9763cd792fb2d3ecebe669e6b1b0b637feee56 ####
#### Current Patch contents ####
pip install cryptography==41.0.5 urllib3==1.26.18 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade curl libcurl3-gnutls libcurl4-openssl-dev libcurl4 python3-urllib3 vim-common vim-runtime vim xxd
