#### First image: sha256:de49d2af8ce36a18ff715468385f2a5025b9223080c4bf6460ff1aec09912894 ####
#### Current Patch contents ####
pip install cryptography==41.0.5 urllib3==1.26.18 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade curl libcurl3-gnutls libcurl4-openssl-dev libcurl4 python3-urllib3 vim-common vim-runtime vim xxd
