#### First image: sha256:52d32b4a9dc0a74f438ca35e3a39f6c3c777ea879ff868cefa34cf64f6ffa893 ####
#### Current Patch contents ####
pip install cryptography==41.0.5 urllib3==1.26.18 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade curl libcurl3-gnutls libcurl4-openssl-dev libcurl4 python3-urllib3 vim-common vim-runtime vim xxd
