#### First image: sha256:2f63c5cf352578b18b8b0d0e1f5a3a38ab1a332db8b1755d447ecc81f9284066 ####
#### Current Patch contents ####
pip install cryptography==41.0.5 urllib3==1.26.18 
python -m pip install --upgrade pip
apt-get update && apt-get install -y --only-upgrade curl libcurl3-gnutls libcurl4-openssl-dev libcurl4 python3-urllib3 vim-common vim-runtime vim xxd
